SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(b.PRICE * s.SALES) as TOTAL_SALES
FROM BOOK_SALES as s
JOIN BOOK as b
    ON s.BOOK_ID = b.BOOK_ID
JOIN AUTHOR as a
    ON b.AUTHOR_ID = a.AUTHOR_ID
WHERE YEAR(s.SALES_DATE) = 2022
    AND MONTH(s.SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC