SELECT DISTINCT c.CAR_ID, c.CAR_TYPE, FLOOR(c.DAILY_FEE*30*(1 - DISCOUNT_RATE*0.01)) as FEE
FROM CAR_RENTAL_COMPANY_CAR as c
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
    ON c.CAR_ID = h.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as d
    ON c.CAR_TYPE = d.CAR_TYPE
        AND d.DURATION_TYPE LIKE "30일 이상"
WHERE c.CAR_TYPE IN ("세단", "SUV")
    AND c.CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-1'
    )
    AND (FLOOR(c.DAILY_FEE*30*(1 - DISCOUNT_RATE*0.01)) BETWEEN 500000 AND (2000000-1))
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC