WITH RANK_DATA as(
    SELECT ID, PERCENT_RANK() OVER(
        ORDER BY SIZE_OF_COLONY DESC
    ) as PERCENT
    FROM ECOLI_DATA
)

SELECT ID, CASE
        WHEN PERCENT<=0.25 THEN "CRITICAL"
        WHEN PERCENT<=0.50 THEN "HIGH"
        WHEN PERCENT<=0.75 THEN "MEDIUM"
        ELSE "LOW"
    END as COLONY_NAME
FROM RANK_DATA
ORDER BY ID ASC