SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) as MONTH, u.GENDER, COUNT(DISTINCT u.USER_ID) as USERS
FROM ONLINE_SALE as o
JOIN USER_INFO as u
    ON o.USER_ID = u.USER_ID
WHERE u.GENDER IS NOT NULL
GROUP BY YEAR(o.SALES_DATE), MONTH(o.SALES_DATE), u.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC