WITH RECURSIVE re_tab as(
    SELECT 1 as GENERATION, ID as SID, ID, PARENT_ID
    FROM ECOLI_DATA
    
    UNION
    
    SELECT GENERATION + 1, c.SID, c.PARENT_ID as ID, p.PARENT_ID as PARENT_ID
    FROM re_tab as c
    JOIN ECOLI_DATA as p
        ON c.PARENT_ID = p.ID
    WHERE c.PARENT_ID IS NOT NULL
)

SELECT COUNT(a.SID) as COUNT, a.GENERATION
FROM re_tab as a
WHERE PARENT_ID IS NULL
    AND NOT EXISTS(
        SELECT *
        FROM re_tab as b
        WHERE a.SID=b.PARENT_ID
    )
GROUP BY a.GENERATION
ORDER BY GENERATION ASC