WITH temp as(
    SELECT CAR_ID as id
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN DATE(START_DATE) AND DATE(END_DATE)
)

SELECT DISTINCT CAR_ID, CASE
                    WHEN EXISTS (SELECT 1 FROM temp WHERE CAR_ID=id) THEN "대여중"
                    ELSE "대여 가능"
                END as AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC