SELECT o.PRODUCT_ID, p.PRODUCT_NAME, SUM(o.AMOUNT*p.PRICE) as TOTAL_SALES
FROM FOOD_ORDER as o
JOIN FOOD_PRODUCT as p
    ON o.PRODUCT_ID = p.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
GROUP BY o.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC