SELECT HISTORY_ID,
    FLOOR((DATEDIFF(h.END_DATE, h.START_DATE)+1) * c.DAILY_FEE * ((100 - COALESCE(d.DISCOUNT_RATE, 0))/100)) as FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
JOIN CAR_RENTAL_COMPANY_CAR as c
    ON h.CAR_ID = c.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as d
    ON c.CAR_TYPE = d.CAR_TYPE
        AND d.DURATION_TYPE=(
            CASE
                WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(h.END_DATE, h.START_DATE)+1 >= 7 THEN '7일 이상'
                ELSE NULL
            END
        )
WHERE c.CAR_TYPE='트럭'
ORDER BY FEE DESC, HISTORY_ID DESC