WITH cte as (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)

SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW as r
JOIN MEMBER_PROFILE as m
    ON r.MEMBER_ID = m.MEMBER_ID
    WHERE r.MEMBER_ID in (SELECT MEMBER_ID FROM cte)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC