SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO as i
JOIN ITEM_TREE as t
ON i.ITEM_ID=t.ITEM_ID
WHERE t.PARENT_ITEM_ID IN (
    SELECT ITEM_ID FROM ITEM_INFO
    WHERE RARITY="RARE"
)
ORDER BY ITEM_ID DESC