WITH monthcar as (
    SELECT MONTH(START_DATE) as MONTH, CAR_ID,
        COUNT(*) OVER(PARTITION BY CAR_ID) as TOTAL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE(START_DATE) BETWEEN DATE("2022-08-01") AND DATE("2022-10-31")
)

SELECT MONTH, CAR_ID, COUNT(*) as RECORDS
FROM monthcar
WHERE TOTAL >= 5
GROUP BY MONTH, CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, CAR_ID DESC