WITH YEAR_TAB as(
    SELECT YEAR(DIFFERENTIATION_DATE) as YEAR, MAX(SIZE_OF_COLONY) as YEAR_MAX
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT y.YEAR, (y.YEAR_MAX - d.SIZE_OF_COLONY) as YEAR_DEV, d.ID
FROM ECOLI_DATA as d
JOIN YEAR_TAB as y
    ON YEAR(d.DIFFERENTIATION_DATE)=y.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC