SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
JOIN CAR_RENTAL_COMPANY_CAR as c
    ON h.CAR_ID = c.CAR_ID
WHERE CAR_TYPE LIKE '세단'
    AND MONTH(START_DATE) = 10
ORDER BY CAR_ID DESC