WITH maxtab as(
    SELECT FISH_TYPE, MAX(LENGTH) as LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO as i
JOIN FISH_NAME_INFO as n
    ON i.FISH_TYPE=n.FISH_TYPE
WHERE LENGTH=(SELECT LENGTH
             FROM maxtab
             WHERE maxtab.FISH_TYPE=i.FISH_TYPE)
ORDER BY ID