WITH ranktab as(
    SELECT EMP_NO, YEAR, SUM(SCORE) as SCORE, ROW_NUMBER() OVER(ORDER BY SUM(SCORE) DESC) as rn
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
)

SELECT r.SCORE, r.EMP_NO, e.EMP_NAME, e.POSITION, e.EMAIL
FROM ranktab as r
JOIN HR_EMPLOYEES as e
    ON r.EMP_NO = e.EMP_NO
WHERE r.rn = 1