WITH ranktab as(
    SELECT BOARD_ID, ROW_NUMBER() OVER(ORDER BY VIEWS DESC) as rn
    FROM USED_GOODS_BOARD
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID IN (
    SELECT BOARD_ID
    FROM ranktab
    WHERE rn=1
)
ORDER BY FILE_ID DESC