SELECT b.CATEGORY, SUM(s.SALES) as TOTAL_SALES
FROM BOOK_SALES as s
JOIN BOOK as b
    ON s.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(s.SALES_DATE, "%Y-%m") LIKE "2022-01"
GROUP BY b.CATEGORY
ORDER BY CATEGORY