WITH maxprice as(
    SELECT CATEGORY, MAX(PRICE) as MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)

SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT as f
WHERE EXISTS (
    SELECT 1
    FROM maxprice as m
    WHERE f.CATEGORY = m.CATEGORY
        AND f.PRICE = m.MAX_PRICE
) AND CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY PRICE DESC